open AdventOfCode2024

// Day1.Part1.runSample() |> printfn "Day 1 Part 1 Test: %d"
// Day1.Part1.runInput() |> printfn "Day 1 Part 1 Actual: %d"
// Day1.Part2.runSample() |> printfn "Day 1 Part 2 Test: %d"
// Day1.Part2.runInput() |> printfn "Day 1 Part 2 Actual: %d"
// Day2.Part1.runSample() |> printfn "Day 2 Part 1 Test: %d"
// Day2.Part1.runInput() |> printfn "Day 2 Part 1 Actual: %d"
// Day2.Part2.runSample() |> printfn "Day 2 Part 2 Test: %d"
// Day2.Part2.runInput() |> printfn "Day 2 Part 2 Actual: %d"
// Day3.Part1.runSample() |> printfn "Day 3 Part 1 Sample: %d"
// Day3.Part1.runInput() |> printfn "Day 3 Part 1 Actual: %d"
// Day3.Part2.runSample() |> printfn "Day 3 Part 2 Sample: %A"
// Day3.Part2.runInput() |> printfn "Day 3 Part 2 Actual: %A"
// Day4.Part1.runSample() |> printfn "Day 4 Part 1 Sample: %A"
// Day4.Part1.runInput() |> printfn "Day 4 Part 1 Actual: %A"
// Day4.Part2.runSample() |> printfn "Day 4 Part 2 Sample: %A"
// Day4.Part2.runInput() |> printfn "Day 4 Part 2 Actual: %A"
// Day5.Part1.runSample() |> printfn "Day 5 Part 1 Sample: %A"
// Day5.Part1.runInput() |> printfn "Day 5 Part 1 Actual: %A"
// Day5.Part2.runSample() |> printfn "Day 5 Part 2 Sample: %A"
// Day5.Part2.runInput() |> printfn "Day 5 Part 2 Actual: %A"
// Day6.Part1.runSample() |> printfn "Day 6 Part 1 Sample: %A"
// Day6.Part1.runInput() |> printfn "Day 6 Part 1 Actual: %A"
// Day6.Part2.runSample() |> printfn "Day 6 Part 2 Sample: %A"
// Day6.Part2.runInput() |> printfn "Day 6 Part 2 Actual: %A"
// Day7.Part1.runSample() |> printfn "Day 7 Part 1 Sample: %A"
// Day7.Part1.runInput() |> printfn "Day 7 Part 1 Actual: %A"
// Day7.Part2.runSample() |> printfn "Day 7 Part 2 Sample: %A"
// Day7.Part2.runInput() |> printfn "Day 7 Part 2 Actual: %A"
// Day8.Part1.runSample() |> printfn "Day 8 Part 1 Sample: %A"
// Day8.Part1.runInput() |> printfn "Day 8 Part 1 Actual: %A"
// Day8.Part2.runSample() |> printfn "Day 8 Part 2 Sample: %A"
// Day8.Part2.runInput() |> printfn "Day 8 Part 2 Actual: %A"

// Day10.Part1.runSample() |> printfn "Day 10 Part 1 Sample: %A"
// Day10.Part1.runInput() |> printfn "Day 10 Part 1 Actual: %A"
// Day10.Part2.runSample() |> printfn "Day 10 Part 2 Sample: %A"
// Day10.Part2.runInput() |> printfn "Day 10 Part 2 Actual: %A"
// Day11.Part1.runSample() |> printfn "Day 11 Part 1 Sample: %A"
// Day11.Part1.runInput() |> printfn "Day 11 Part 1 Actual: %A"
// Day11.Part2.runSample() |> printfn "Day 11 Part 2 Sample: %A"
// Day11.Part2.runInput() |> printfn "Day 11 Part 2 Actual: %A"
// Day12.Part1.runSample() |> printfn "Day 12 Part 1 Sample: %A"
// Day12.Part1.runInput() |> printfn "Day 12 Part 1 Actual: %A"
// Day12.Part2.runSample() |> printfn "Day 12 Part 2 Sample: %A"
// Day12.Part2.runInput() |> printfn "Day 12 Part 2 Actual: %A"
// Day13.Part1.runSample() |> printfn "Day 13 Part 1 Sample: %A"
// Day13.Part1.runInput() |> printfn "Day 13 Part 1 Actual: %A"
// Day13.Part2.runSample() |> printfn "Day 13 Part 2 Sample: %A"
// Day13.Part2.runInput() |> printfn "Day 13 Part 2 Actual: %A"
// Day14.Part1.runSample() |> printfn "Day 14 Part 1 Sample: %A"
// Day14.Part1.runInput() |> printfn "Day 14 Part 1 Actual: %A"
// Day14.Part2.runInput() |> printfn "Day 14 Part 2 Actual: %A"
// Day15.Part1.runSample() |> printfn "Day 15 Part 1 Sample: %A"
// Day15.Part1.runInput() |> printfn "Day 15 Part 1 Actual: %A"
// Day15.Part2.runSample() |> printfn "Day 15 Part 2 Sample: %A"
// Day15.Part2.runInput() |> printfn "Day 15 Part 2 Actual: %A"
// Day16.Part1.runSample() |> printfn "Day 16 Part 1 Sample: %A"
// Day16.Part1.runInput() |> printfn "Day 16 Part 1 Actual: %A"
// Day16.Part2.runSample() |> printfn "Day 16 Part 2 Sample: %A"
// Day16.Part2.runInput() |> printfn "Day 16 Part 2 Actual: %A"
// Day17.Part1.runSample() |> printfn "Day 17 Part 1 Sample: %A"
// Day17.Part1.runInput() |> printfn "Day 17 Part 1 Actual: %A"
// Day17.Part2.runSample() |> printfn "Day 17 Part 2 Sample: %A"
// Day17.Part2.runInput() |> printfn "Day 17 Part 2 Actual: %A"
// Day18.Part1.runSample() |> printfn "Day 18 Part 1 Sample: %A"
// Day18.Part1.runInput() |> printfn "Day 18 Part 1 Actual: %A"
Day18.Part2.runSample() |> printfn "Day 18 Part 2 Sample: %A"
Day18.Part2.runInput() |> printfn "Day 18 Part 2 Actual: %A"

System.Console.ReadLine() |> ignore
